spark:
    app-name: Spark Spike
    master: local[*]
    data-directory: classpath:data/
spring:
  freemarker:
    suffix: .ftlh
    cache: false
    template-loader-path:
      - classpath:/templates/
